export { ProductTemplate1 } from './template1'
export { ProductTemplate2 } from './template2'
export { ProductTemplate3 } from './template3'
export { DynamicProductDetail } from './dynamic-product-detail'
export { ProductTemplateSelector } from './template-selector'
export { ProductTemplateSkeleton } from './product-template-skeleton' 